configfile:'configfile.yaml'
import quantities as pq

# Loading parameters
spectra = config['spectra']

# Deriving the window lengths to use 
winlens = [10]

# Rule collecting all the outputs    
rule all:
    input:
        expand('../results/{spectrum}/winlen{w}/filtered_patterns.npy', spectrum=spectra, w=winlens) +
        expand('../results/{spectrum}/winlen{w}/data_results.npy', spectrum=spectra, w=winlens) 


# Rule to analyze the data (no filtering applied yet)
rule analyze_data:
    input:
        script = 'spade_analysis.py'
    output:
        '../results/{spectrum}/winlen{w}/data_results.npy'
    shell:
        "mpirun python  {input.script} "

# Rule to filter the data using Pattern Spectrum Filtering
rule filter_results:
    input:
        results = '../results/{spectrum}/winlen{w}/data_results.npy',
        script = 'filter_results.py'
    output:
        '../results/{spectrum}/winlen{w}/filtered_patterns.npy'
    shell:
        "python {input.script} '{wildcards.spectrum}' '{wildcards.w}'"
