configfile:'configfile.yaml'
import quantities as pq

# Loading parameters
sess_ids = range(113) 
# sess_ids = [23]

# Deriving the window lengths to use 
winlens = [8]

# Rule collecting all the outputs    
rule all:
    input:
        expand('../results/{session_id}/winlen{w}/filtered_patterns.npy', session_id=sess_ids, w=winlens) +
        expand('../results/{session_id}/winlen{w}/data_results.npy', session_id=sess_ids, w=winlens) 


# Rule to analyze the data (no filtering applied yet)
rule analyze_data:
    input:
        script = 'spade_analysis.py'
    output:
        '../results/{session_id}/winlen{w}/data_results.npy'
    shell:
        "mpirun python  {input.script} '{wildcards.w}' '{wildcards.session_id}' "

# Rule to filter the data using Pattern Spectrum Filtering
rule filter_results:
    input:
        results = '../results/{session_id}/winlen{w}/data_results.npy',
        script = 'filter_results.py'
    output:
        '../results/{session_id}/winlen{w}/filtered_patterns.npy'
    shell:
        "python {input.script} '{wildcards.session_id}' '{wildcards.w}'"
